// frontend/src/components/ui/page-header.tsx
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';

interface PageHeaderProps {
  title: string;
  subtitle?: string;
  years?: string[] | number[];
  selectedYear?: string | number | null;
  onYearChange?: (year: string | null) => void;
  children?: React.ReactNode;
}

export function PageHeader({ title, subtitle, years, selectedYear, onYearChange, children }: PageHeaderProps) {
  return (
    <div className="flex items-start justify-between mb-6">
      <div>
        <h1 className="text-2xl font-semibold tracking-tight text-foreground">{title}</h1>
        {subtitle && <p className="text-sm text-muted-foreground mt-0.5">{subtitle}</p>}
      </div>
      <div className="flex items-center gap-2">
        {years && years.length > 0 && onYearChange && (
          <Select
            value={selectedYear !== null && selectedYear !== undefined ? String(selectedYear) : 'all'}
            onValueChange={onYearChange}
          >
            <SelectTrigger className="w-28 h-8 text-sm">
              <SelectValue>
                {selectedYear !== null && selectedYear !== undefined && String(selectedYear) !== 'all'
                  ? String(selectedYear)
                  : 'Alle Jahre'}
              </SelectValue>
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">Alle Jahre</SelectItem>
              {years.map(y => (
                <SelectItem key={y} value={String(y)}>{y}</SelectItem>
              ))}
            </SelectContent>
          </Select>
        )}
        {children}
      </div>
    </div>
  );
}

// frontend_svelte/src/lib/PageHeader.svelte
<script lang="ts">
	interface Props {
		title: string;
		subtitle?: string;
		years?: string[];
		selectedYear?: string;
		allLabel?: string;
		onchange?: () => void;
	}

	let {
		title,
		subtitle,
		years = [],
		selectedYear = $bindable(''),
		allLabel = 'Alle Jahre',
		onchange,
	}: Props = $props();
</script>

<div class="flex flex-wrap items-center justify-between gap-4">
	<div>
		<h1 class="text-2xl font-bold">{title}</h1>
		{#if subtitle}
			<p class="text-xs text-gray-500 mt-0.5">{subtitle}</p>
		{/if}
	</div>
	{#if years.length > 0}
		<select
			bind:value={selectedYear}
			{onchange}
			class="bg-gray-800 border border-gray-700 rounded px-3 py-1.5 text-sm text-gray-200 focus:outline-none focus:border-orange-500"
		>
			<option value="">{allLabel}</option>
			{#each years as y}
				<option value={y}>{y}</option>
			{/each}
		</select>
	{/if}
</div>
